import {
  Package,
  Shirt,
  Watch,
  Headphones,
  Gamepad2,
  Book,
} from "lucide-react";

export const categories = [
  {
    id: "sneakers",
    name: "Sneakers & Shoes",
    icon: Package,
    image: "/storage/v1/object/public/static-assets/sneakers.webp",
    brands: [
      "Nike",
      "Adidas",
      "Jordan",
      "Converse",
      "Vans",
      "New Balance",
      "Puma",
      "Reebok",
    ],
    sizes: [
      "US 6",
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 13",
    ],
    hasSize: true,
    hasBrand: true,
    hasModel: true,
  },
  {
    id: "clothing",
    name: "Clothing & Apparel",
    icon: Shirt,
    image: "/storage/v1/object/public/static-assets/clothing.webp",
    brands: [
      "Nike",
      "Adidas",
      "Supreme",
      "Off-White",
      "Stone Island",
      "Kith",
      "Fear of God",
      "Essentials",
    ],
    sizes: ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
    hasSize: true,
    hasBrand: true,
    hasModel: false,
  },
  {
    id: "accessories",
    name: "Accessories",
    icon: Watch,
    image: "/storage/v1/object/public/static-assets/accessories.webp",
    brands: [
      "Rolex",
      "Omega",
      "Casio",
      "G-Shock",
      "Apple",
      "Samsung",
      "Louis Vuitton",
      "Gucci",
    ],
    sizes: [],
    hasSize: false,
    hasBrand: true,
    hasModel: true,
  },
  {
    id: "electronics",
    name: "Electronics",
    icon: Headphones,
    image: "/storage/v1/object/public/static-assets/electronics.webp",
    brands: [
      "Apple",
      "Samsung",
      "Sony",
      "Bose",
      "Nintendo",
      "PlayStation",
      "Xbox",
      "Google",
    ],
    sizes: [],
    hasSize: false,
    hasBrand: true,
    hasModel: true,
  },
  {
    id: "gaming",
    name: "Gaming",
    icon: Gamepad2,
    image: "/storage/v1/object/public/static-assets/gaming.webp",
    brands: [
      "Nintendo",
      "PlayStation",
      "Xbox",
      "Steam",
      "Razer",
      "Logitech",
      "Corsair",
      "SteelSeries",
    ],
    sizes: [],
    hasSize: false,
    hasBrand: true,
    hasModel: true,
  },
  {
    id: "collectibles",
    name: "Collectibles & Art",
    icon: Book,
    image: "/storage/v1/object/public/static-assets/collectibles.webp",
    brands: [
      "Funko",
      "Hot Toys",
      "KAWS",
      "Bearbrick",
      "Pokemon",
      "Marvel",
      "DC Comics",
      "Disney",
    ],
    sizes: [],
    hasSize: false,
    hasBrand: true,
    hasModel: true,
  },
];
