import {
  Package,
  Shirt,
  Watch,
  Headphones,
  Gamepad2,
  Book,
} from "lucide-react";
import {
  SNEAKER_BRANDS,
  CLOTHING_BRANDS,
  ACCESSORY_BRANDS,
  ELECTRONIC_BRANDS,
  GAMING_BRANDS,
  COLLECTIBLE_BRANDS,
  SNEAKER_SIZES,
  CLOTHING_SIZES,
  CATEGORY_IDS,
} from "./enums";

export const categories = [
  {
    id: CATEGORY_IDS.SNEAKERS,
    name: "Sneakers & Shoes",
    icon: Package,
    image: "/storage/v1/object/public/static-assets/sneakers.webp",
    brands: Object.values(SNEAKER_BRANDS),
    sizes: Object.values(SNEAKER_SIZES),
    hasSize: true,
    hasBrand: true,
    hasModel: true,
  },
  {
    id: CATEGORY_IDS.CLOTHING,
    name: "Clothing & Apparel",
    icon: Shirt,
    image: "/storage/v1/object/public/static-assets/clothing.webp",
    brands: Object.values(CLOTHING_BRANDS),
    sizes: Object.values(CLOTHING_SIZES),
    hasSize: true,
    hasBrand: true,
    hasModel: false,
  },
  {
    id: CATEGORY_IDS.ACCESSORIES,
    name: "Accessories",
    icon: Watch,
    image: "/storage/v1/object/public/static-assets/accessories.webp",
    brands: Object.values(ACCESSORY_BRANDS),
    sizes: [],
    hasSize: false,
    hasBrand: true,
    hasModel: true,
  },
  {
    id: CATEGORY_IDS.ELECTRONICS,
    name: "Electronics",
    icon: Headphones,
    image: "/storage/v1/object/public/static-assets/electronics.webp",
    brands: Object.values(ELECTRONIC_BRANDS),
    sizes: [],
    hasSize: false,
    hasBrand: true,
    hasModel: true,
  },
  {
    id: CATEGORY_IDS.GAMING,
    name: "Gaming",
    icon: Gamepad2,
    image: "/storage/v1/object/public/static-assets/gaming.webp",
    brands: Object.values(GAMING_BRANDS),
    sizes: [],
    hasSize: false,
    hasBrand: true,
    hasModel: true,
  },
  {
    id: CATEGORY_IDS.COLLECTIBLES,
    name: "Collectibles & Art",
    icon: Book,
    image: "/storage/v1/object/public/static-assets/collectibles.webp",
    brands: Object.values(COLLECTIBLE_BRANDS),
    sizes: [],
    hasSize: false,
    hasBrand: true,
    hasModel: true,
  },
];
